language: java
jdk: oraclejdk8
branches:
  only: master
install: true
before_script:
 - "export DISPLAY=:99.0"
 - "sh -e /etc/init.d/xvfb start"
 - sleep 3 # give xvfb some time to start
 - chmod +x .travis/build.sh
script: ".travis/build.sh"
